name: JavaScript Checks

on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - main

concurrency:
  group: js-checks-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  changed-files:
    name: Check Changed Files
    runs-on: ubuntu-latest
    outputs:
      any_changed: ${{ steps.changed.outputs.any_changed }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check if any JavaScript files have changed
        id: changed
        uses: tj-actions/changed-files@ed68ef82c095e0d48ec87eccea555d944a631a4c
        with:
          files: |
            apps/client-js/**
            libs/moqtail-ts/**

  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest
    needs: changed-files
    if: needs.changed-files.outputs.any_changed == 'true'
    strategy:
      fail-fast: false
      matrix:
        job: [build, format, test]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Run ${{ matrix.job }}
        run: npm run ${{ matrix.job }}
